import type { AgentMessage } from "@oh-my-pi/pi-agent-core";
import type {
	ImageContent,
	MessageAttribution,
	ServiceTierByFamily,
	StopReason,
	TextContent,
	Usage,
} from "@oh-my-pi/pi-ai";
import type { StructuredSubagentSchemaMode } from "@oh-my-pi/pi-tui/tools/task";
import type { CompactionMethod } from "./compaction-methods";

export const CURRENT_SESSION_VERSION = 3;

export const SESSION_TITLE_SLOT_BYTES = 256;

export const SESSION_TITLE_SLOT_ENTRY_TYPE = "title";

export const TITLE_CHANGE_ENTRY_TYPE = "title_change";

export const APPROVAL_ENTRY_TYPE = "approval";

export const TURN_ENTRY_TYPE = "turn";

export type SessionTitleSource = "auto" | "user";

/** Fixed-width first-line slot carrying the mutable current session title. */
export interface SessionTitleSlotEntry {
	type: typeof SESSION_TITLE_SLOT_ENTRY_TYPE;
	v: 1;
	title: string;
	source?: SessionTitleSource;
	updatedAt: string;
	pad: string;
}

export const EPHEMERAL_MODEL_CHANGE_ROLE = "fallback";

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	title?: string; // Auto-generated title from first message
	titleSource?: SessionTitleSource;
	timestamp: string;
	cwd: string;
	/**
	 * Additional workspace directories beyond `cwd` (multi-root workspace).
	 * Absolute, normalized, deduplicated. Absent on legacy single-cwd sessions.
	 * See {@link SessionWorkspace} in `./session-workspace`.
	 */
	additionalDirectories?: string[];
	parentSession?: string;
	/** Prior absolute JSONL locations recorded by successful session moves. */
	previousSessionFiles?: string[];
	/** Provider prompt-cache identity inherited by exact-route full forks. */
	providerPromptCacheKey?: string;
}

export interface NewSessionOptions {
	parentSession?: string;
	/** Provider prompt-cache identity to seed on the new session header. */
	providerPromptCacheKey?: string;
	/** Skip flushing the current session and delete it instead of saving. */
	drop?: boolean;
	/** Additional workspace directories to seed on the new session. */
	additionalDirectories?: string[];
	/** Directory for the new session file (and later `/new` sessions); defaults to the current session directory. */
	sessionDir?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

/** Usage from a model call that does not belong in the conversation transcript. */
export interface ModelUsageEntry extends SessionEntryBase {
	type: "model_usage";
	purpose: string;
	/** Resolved model role used for the call, such as `tiny` or `smol`. */
	role?: string;
	api: string;
	provider: string;
	model: string;
	usage: Usage;
	stopReason: StopReason;
	errorMessage?: string;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel?: string | null;
	/**
	 * The user-configured selector at the time of this change: `"auto"` when auto
	 * mode was active, otherwise the concrete level. Absent on entries written
	 * before auto-mode persistence existed; readers fall back to `thinkingLevel`.
	 */
	configured?: string | null;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	/** Model in "provider/modelId" format */
	model: string;
	/** Role: "default", "smol", "slow", etc. Undefined treated as "default" */
	role?: string;
	/** True when this transition selected a retry-fallback model rather than the configured model. */
	resolvedModelIsFallback?: boolean;
}

export interface ServiceTierChangeEntry extends SessionEntryBase {
	type: "service_tier_change";
	serviceTier: ServiceTierByFamily | null;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	shortSummary?: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Estimated context tokens after the rewrite (display metadata). */
	tokensAfter?: number;
	/** Method that produced this entry; absent on legacy sessions and extension-provided compactions. */
	method?: CompactionMethod;
	/** Last branch entry represented by provider-native replay history; later entries replay normally. */
	providerReplayThroughEntryId?: string;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Hook-provided data to persist across compaction */
	preserveData?: Record<string, unknown>;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromExtension?: boolean;
	/**
	 * Dead-end warning from the post-pass progress guard: the pass completed
	 * but freed too little for maintenance to continue. Rendered on the
	 * compaction divider.
	 */
	warning?: string;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromExtension?: boolean;
}

/**
 * Pure marker entry recorded by `/clear` (resetSessionContext). It carries no
 * payload — its presence on the branch is a durable boundary the collapsed
 * live transcript and the model-context rebuild start emission after, so a
 * rebuild (theme change, focus attach, /shake, resume) does not resurrect the
 * pre-reset conversation. The on-disk record and the plain `transcript:true`
 * export path keep the full pre-reset history.
 */
export interface ResetBoundaryEntry extends SessionEntryBase {
	type: "reset_boundary";
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Append-only audit entry recording a session title change. */
export interface TitleChangeEntry extends SessionEntryBase {
	type: typeof TITLE_CHANGE_ENTRY_TYPE;
	title: string;
	previousTitle?: string;
	source: SessionTitleSource;
	trigger?: string;
}

/**
 * One half of an approval audit pair: what was asked, and what was decided.
 *
 * ## Why this is in the log and not in the model's context
 *
 * Structurally, not by a filter. `SessionMessageEntry` is the only union member
 * that carries an `AgentMessage`, so every other entry is metadata the model
 * cannot receive — which is why `TitleChangeEntry` needs no special handling
 * either. That is also why there is deliberately no `EPHEMERAL_*` sentinel here:
 * that marker exists for `model_change`, which *does* change what the model sees
 * mid-turn. An approval record changes nothing about the conversation, and adding
 * a marker for it would be a state nothing reads.
 *
 * ## Why a pair rather than one record
 *
 * After a crash the question is "who approved this". A record written only at the
 * answer cannot distinguish a denial from a process that died while the prompt was
 * open, and a record written only at the ask cannot say what was decided. So both
 * halves are written, and they share `requestId`.
 *
 * ## What is recorded, and from where
 *
 * `policyKey` is whatever `resolveApproval` reported — the key that actually
 * decided this call — rather than the tool name the call site knows. Those differ
 * whenever a tool declares a narrower policy key or inherits a renamed tool's, and
 * the audit trail has to name the rule that fired, not the tool that asked.
 */
export interface ApprovalEntry extends SessionEntryBase {
	type: typeof APPROVAL_ENTRY_TYPE;
	/** Ties the `asked` and `answered` halves of one prompt together. */
	requestId: string;
	phase: "asked" | "answered";
	toolName: string;
	/** The key `resolveApproval` resolved the policy under. Present on both halves. */
	policyKey?: string;
	/** The policy in force when the question was asked. */
	policy?: string;
	/** What the user chose. `asked` has none. */
	decision?: string;
	/** Whether an ACP client answered rather than a local prompt. */
	source?: "user" | "mode" | "tool" | "acp";
}

/**
 * One half of a turn's durable record: when it opened, and how it closed.
 *
 * ## Why it is written on the event, not on the loop's `turnOpen` flag
 *
 * Three sites in `runLoopBody` push `turn_start` and then throw
 * (`agent-loop.ts:1243` `getSteeringMessages`, `:1381` `beforeModelCall`,
 * `:1397` `onToolChoiceRejected`), so `turn_end` never fires for those turns.
 * A record written only on close would be missing exactly the turns that died.
 * `agent-loop.ts:1243` also opens a turn with a bare `stream.push` and never
 * assigns the flag, so the flag and the stream disagree at one of the three
 * sites: keying the write on the event cannot inherit that bug, and keying it
 * on the flag would.
 *
 * ## Why `blockedBy` is a reference and not a copy
 *
 * `ApprovalEntry` already holds the decision, the policy key, and the source.
 * Duplicating those fields here would create a second source of truth that can
 * drift from the first, so this names the `requestId`s and leaves the content
 * where it is already written.
 */
/**
 * True for the `answered` half of an approval that refused the call.
 *
 * A deny-list over what refusal *looks like*, not an allow-list of one
 * producer's enum, because `decision` has no single vocabulary: the ACP bridge
 * writes option kinds (`reject_once` / `reject_always`), a tool-level gate can
 * answer `"denied"`, and an extension may write any string through
 * `ExtensionRunner.recordApprovalEntry`. `policy: "deny"` is accepted too — it is
 * the one field a gate denial sets regardless of how the question was answered.
 *
 * Only the `answered` half qualifies, so one refusal yields one `requestId` even
 * though the pair writes two entries.
 */
export function isApprovalDenial(entry: SessionEntry): entry is ApprovalEntry {
	if (entry.type !== APPROVAL_ENTRY_TYPE || entry.phase !== "answered") return false;
	if (entry.policy === "deny") return true;
	const decision = entry.decision;
	if (!decision) return false;
	return decision === "denied" || decision === "deny" || decision.startsWith("reject");
}

export interface TurnEntry extends SessionEntryBase {
	type: typeof TURN_ENTRY_TYPE;
	/** Index of the turn within the session; matches the loop's `turnIndex`. */
	turnIndex: number;
	phase: "started" | "ended";
	/**
	 * `ApprovalEntry.requestId` of every approval refused while this turn was open.
	 *
	 * "Refused", not "cut short": a rejected tool call does not end the turn — the
	 * model receives the rejection and continues. The turns that actually die are
	 * the three sites in `runLoopBody` that push `turn_start` and then throw, and a
	 * denial is not what kills them. So this records that the turn was *subject to*
	 * a gate refusal, which is observable, rather than a causal claim about the
	 * turn's end, which is not.
	 *
	 * ## Scope: bounded by what `ApprovalEntry` actually records
	 *
	 * Read back off the log, so it can only name refusals that reached the log. As
	 * of this writing exactly two paths append approval halves — the extension tool
	 * wrapper and the ACP permission path — and the interactive tool path writes
	 * none: a core tool (bash under a `deny` policy, say) is refused without leaving
	 * an `ApprovalEntry` to point at. That gap predates this field; it is the audit
	 * entry's, not this one's.
	 *
	 * Stated here rather than left to the name: `blockedBy` is absent or short for
	 * the refusals nobody recorded, and widening coverage means recording those
	 * refusals first, not widening this scan.
	 *
	 * Deliberately not derived from `ToolResultMessage.isError`: that flag carries
	 * no policy, so it cannot tell a gate denial from an ordinary tool failure.
	 * Filling this from it would build a second source that disagrees with
	 * `ApprovalEntry` in exactly the cases that matter.
	 */
	blockedBy?: string[];
}

declare module "@oh-my-pi/pi-agent-core/compaction/entries" {
	interface CustomCompactionSessionEntries {
		titleChange: TitleChangeEntry;
		credentialPin: CredentialPinEntry;
		modelUsage: ModelUsageEntry;
		approval: ApprovalEntry;
		turn: TurnEntry;
	}
}

/** TTSR injection entry - tracks which time-traveling rules have been injected this session. */
export interface TtsrInjectionEntry extends SessionEntryBase {
	type: "ttsr_injection";
	/** Names of rules that were injected */
	injectedRules: string[];
}

/**
 * Records which OAuth account served this session's requests for a provider.
 *
 * Provider prompt caches (Anthropic in particular) are account-scoped, and the
 * auth store's session-sticky routing is process-local under a remote auth
 * broker, so resume must re-pin the same account to reuse the warm cache
 * prefix. Stores a sha-256 of the account + billing-scope tuple instead of
 * the raw email/uuid/org; note an unsalted digest of a guessable email is
 * still linkable, so exported sessions are pseudonymous, not anonymous.
 */
export interface CredentialPinEntry extends SessionEntryBase {
	type: "credential_pin";
	/** Provider id the pin applies to (e.g. "anthropic"). */
	provider: string;
	/** `credentialPinHash()` of the serving account's identity + scope tuple. */
	hash: string;
}

/** Session init entry - captures initial context for subagent sessions (debugging/replay). */
export interface SessionInitEntry extends SessionEntryBase {
	type: "session_init";
	/** Full system prompt sent to the model */
	systemPrompt: string;
	/** Initial task/user message */
	task: string;
	/** Tools available to the agent */
	tools: string[];
	/** Agent definition name (for example `scout` or `reviewer`). */
	agent?: string;
	/** Semantic model role declared by the agent, retained even after concrete model resolution. */
	modelRole?: string;
	/** Initially resolved provider/model selector for historical display. */
	resolvedModel?: string;
	/** Whether the agent definition is read-only, allowing an exact zero-LoC attribution. */
	readOnly?: boolean;
	/** Output schema if structured output was requested. */
	outputSchema?: unknown;
	/** Enforcement policy recorded with the output schema for faithful revival. */
	outputSchemaMode?: StructuredSubagentSchemaMode;
	/** Whether revival must retain only the explicitly persisted tool names. */
	restrictToolNames?: boolean;
	/** Spawn allowlist the subagent ran with ("" = none, "*" = any, else CSV); absent on pre-spawns files. */
	spawns?: string;
	/** The agent's `readSummarize` setting (`false` = read summarization disabled); absent uses the session default. */
	readSummarize?: boolean;
	/** Effective advisor for this subagent: `"on"` = advisor-role model, else an explicit model pattern; absent = unadvised. */
	advisor?: string;
	/** Effective thresholds for a child with an explicit compaction override. */
	compactionThreshold?: { thresholdPercent: number; thresholdTokens: number };
	/** True when the subagent ran inside an isolation worktree: never revivable, transcript-only after park. Absent on older files. */
	isolated?: boolean;
}

/** Mode change entry - tracks agent mode transitions (e.g. plan mode). */
export interface ModeChangeEntry extends SessionEntryBase {
	type: "mode_change";
	/** Current mode name, or "none" when exiting a mode */
	mode: string;
	/** Optional mode-specific data (e.g. plan file path) */
	data?: Record<string, unknown>;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content participates in LLM context through convertToLlm().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
	/** Who initiated this message for billing/attribution semantics. */
	attribution?: MessageAttribution;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ModelUsageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| ServiceTierChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| TitleChangeEntry
	| TtsrInjectionEntry
	| SessionInitEntry
	| ModeChangeEntry
	| CredentialPinEntry
	| ApprovalEntry
	| TurnEntry
	| ResetBoundaryEntry;

/** Raw logical file entry after loaders strip any fixed-width title slot. */
export type FileEntry = SessionHeader | SessionEntry;

/** Physical JSONL entry before slot-aware loaders fold the title slot. */
export type RawFileEntry = SessionTitleSlotEntry | FileEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
}

export interface UsageStatistics {
	input: number;
	output: number;
	cacheRead: number;
	cacheWrite: number;
	totalTokens: number;
	orchestrationInput: number;
	orchestrationOutput: number;
	orchestrationCacheRead: number;
	premiumRequests: number;
	cost: number;
}
/**
 * True when a raw JSONL line is a complete `message` record carrying an
 * assistant role. Parses the line, so valid JSON whitespace (`"role" :
 * "assistant"`, tabs, newlines-in-string excluded by line framing) classifies
 * correctly — unlike substring checks for exact serializations. Malformed or
 * partial lines (mid-write truncation) return false.
 */
export function isAssistantMessageLine(line: string): boolean {
	if (line.length === 0 || line.charCodeAt(0) !== 123) return false;
	let record: { type?: unknown; message?: { role?: unknown } };
	try {
		record = JSON.parse(line) as { type?: unknown; message?: { role?: unknown } };
	} catch {
		return false;
	}
	return record.type === "message" && record.message?.role === "assistant";
}
