/**
 * The closed peer-name space.
 *
 * NOTICE — this file is carried from an MIT-licensed reference with an added
 * OpenAI/Anthropic rider. Owner decision 2026-10-04: this repository is neither
 * Anthropic's nor OpenAI's, so the content is used with attribution.
 *
 *   source:   mcp_agent_mail_rust (https://github.com/Dicklesworthstone/mcp_agent_mail_rust)
 *   commit:   21a25c2bcfd20c9b31bcb109c294d17411eb5ba1
 *   file:     crates/mcp-agent-mail-core/src/models.rs
 *   symbols:  VALID_ADJECTIVES (line 331), VALID_NOUNS (line 412)
 *
 * The rider defines "use" to include copying and analysing, and names Anthropic
 * PBC a Restricted Party; that was weighed and the decision recorded in
 * `NOTICE` at the package root.
 *
 * These are colours, weather and character words, and landforms, animals,
 * birds, fish, trees and structures. No entry names a job, a subsystem or a
 * capability — which is why allocation draws from them.
 *
 * `/rename` accepts an arbitrary string and therefore breaks the role-free
 * property for *renamed* peers; it survives only for *allocated* names. Do not
 * "restore" the guarantee by rejecting non-space names here — that hole is the
 * owner's decision, and the remaining defence is the trust layer.
 */

/** 75 adjectives. */
export const ADJECTIVES: readonly string[] = [
	"red",
	"orange",
	"yellow",
	"pink",
	"black",
	"purple",
	"blue",
	"brown",
	"white",
	"green",
	"chartreuse",
	"lilac",
	"fuchsia",
	"azure",
	"amber",
	"coral",
	"crimson",
	"cyan",
	"gold",
	"golden",
	"gray",
	"indigo",
	"ivory",
	"jade",
	"lavender",
	"magenta",
	"maroon",
	"navy",
	"olive",
	"pearl",
	"rose",
	"ruby",
	"sage",
	"scarlet",
	"silver",
	"teal",
	"topaz",
	"violet",
	"cobalt",
	"copper",
	"bronze",
	"emerald",
	"sapphire",
	"turquoise",
	"beige",
	"tan",
	"cream",
	"peach",
	"plum",
	"sunny",
	"misty",
	"foggy",
	"stormy",
	"windy",
	"frosty",
	"dusty",
	"hazy",
	"cloudy",
	"rainy",
	"snowy",
	"icy",
	"mossy",
	"sandy",
	"swift",
	"quiet",
	"bold",
	"calm",
	"bright",
	"dark",
	"wild",
	"silent",
	"gentle",
	"rustic",
	"noble",
	"proud",
];

/** 132 nouns. */
export const NOUNS: readonly string[] = [
	"stone",
	"lake",
	"creek",
	"pond",
	"mountain",
	"hill",
	"snow",
	"castle",
	"river",
	"forest",
	"valley",
	"canyon",
	"meadow",
	"prairie",
	"desert",
	"island",
	"cliff",
	"cave",
	"glacier",
	"waterfall",
	"spring",
	"stream",
	"reef",
	"dune",
	"ridge",
	"peak",
	"gorge",
	"marsh",
	"brook",
	"glen",
	"grove",
	"fern",
	"hollow",
	"basin",
	"cove",
	"bay",
	"harbor",
	"coast",
	"shore",
	"bluff",
	"knoll",
	"summit",
	"plateau",
	"dog",
	"cat",
	"bear",
	"fox",
	"wolf",
	"deer",
	"elk",
	"moose",
	"otter",
	"beaver",
	"badger",
	"lynx",
	"puma",
	"squirrel",
	"rabbit",
	"hare",
	"mouse",
	"mink",
	"seal",
	"horse",
	"lion",
	"tiger",
	"panther",
	"leopard",
	"jaguar",
	"coyote",
	"bison",
	"ox",
	"hawk",
	"eagle",
	"owl",
	"falcon",
	"raven",
	"heron",
	"crane",
	"finch",
	"robin",
	"sparrow",
	"duck",
	"goose",
	"swan",
	"dove",
	"wren",
	"jay",
	"lark",
	"kite",
	"condor",
	"osprey",
	"pelican",
	"gull",
	"tern",
	"stork",
	"ibis",
	"cardinal",
	"oriole",
	"thrush",
	"trout",
	"salmon",
	"bass",
	"pike",
	"carp",
	"turtle",
	"frog",
	"pine",
	"oak",
	"maple",
	"birch",
	"cedar",
	"willow",
	"aspen",
	"elm",
	"orchid",
	"lotus",
	"ivy",
	"tower",
	"bridge",
	"forge",
	"mill",
	"barn",
	"gate",
	"anchor",
	"lantern",
	"beacon",
	"compass",
	"horizon",
	"spire",
	"chapel",
	"citadel",
	"fortress",
];

/** 9,900 — a finite, measurable space rather than a surprise. */
export const NAME_SPACE_SIZE = ADJECTIVES.length * NOUNS.length;

/** Grapheme budget for a display name, matching the reference implementation. */
export const NAME_GRAPHEME_LIMIT = 64;
